name: Deploy to Railway

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test imports
      run: |
        python -c "import fastapi, uvicorn, langchain_community"
    
    - name: Validate configuration
      run: |
        python -c "from config import Config; print('Config validation passed')"
      env:
        GEMINI_API_KEY: dummy_key_for_testing
        BEARER_TOKEN: dummy_token_for_testing

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Railway
      uses: bervProject/railway-deploy@v1.0.0
      with:
        service: ${{ secrets.RAILWAY_SERVICE_ID }}
        token: ${{ secrets.RAILWAY_TOKEN }}
